Table users {
    id int [pk, increment]
    name varchar
    email varchar
    imageUrl varchar
}

Table eventTypes {
    id int [pk, increment]
    name varchar
    description varchar
}

Table bookings {
    id int [pk, increment]
    userId int [ref: > users.id]
    eventTypeId int [ref: > eventTypes.id]
    location varchar [ref: > locations.id]
    date date
}

Table locations {
    id int [pk, increment]
    city varchar

}

Table artistLocations {
    id int [pk, increment]
    locationId int [ref: > locations.id]
    userId int [ref:> users.id]
}


// Table bands {
//     id int [pk, increment]
//     bandName varchar
//     userId int [ref: > users.id]
//     description varchar
//     rate int
// }



// Table djs {
//     id int [pk, increment]
//     name varchar
//     userId int [ref: > users.id]
//     description varchar
//     rate int
// }








